defaults: &defaults
  adapter: postgresql
  encoding: utf8
  username: sander
  #password: i53slep
  timeout: 5000
  
development:
  database: messagemap_dev
  <<: *defaults
  
test:
  database: messagemap_test
  <<: *defaults

production:
  database: messagemap_prod
  <<: *defaults
