development:
  adapter: postgresql
  database: messagemap_dev
  username: msgmap
  password: i53slep
  timeout: 5000

test:
  adapter: postgresql
  database: messagemap_test
  username: msgmap
  password: i53slep
  timeout: 5000

production:
  adapter: postgresql
  database: messagemap_prod
  username: msgmap
  password: i53slep
  timeout: 5000
